# Netlify configuration file
[build]
  publish = "."

[[redirects]]
  from = "/property/*"
  to = "/property-demo.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"